export const bikes = [
  { type: ["Road / Racing"], name: "Bike 1", city: "Kyiv", price: 1200 },
  { type: ["Mountain / Trail"], name: "Bike 2", city: "Lviv", price: 3500 },
  { type: ["Electric / e-Bike"], name: "Bike 3", city: "Odessa", price: 800 },
  {
    type: ["Gravel / Adventure"],
    name: "Bike 4",
    city: "Kharkiv",
    price: 5000,
  },
  { type: ["Hybrid / Commuter"], name: "Bike 5", city: "Dnipro", price: 2100 },
  { type: ["Road / Racing"], name: "Bike 6", city: "Vinnytsia", price: 4100 },
  {
    type: ["Mountain / Trail"],
    name: "Bike 7",
    city: "Chernihiv",
    price: 2700,
  },
  { type: ["Electric / e-Bike"], name: "Bike 8", city: "Lutsk", price: 600 },
  { type: ["Gravel / Adventure"], name: "Bike 9", city: "Rivne", price: 4800 },
  {
    type: ["Hybrid / Commuter"],
    name: "Bike 10",
    city: "Ivano-Frankivsk",
    price: 3300,
  },
  { type: ["Road / Racing"], name: "Bike 11", city: "Ternopil", price: 900 },
  { type: ["Mountain / Trail"], name: "Bike 12", city: "Kherson", price: 2500 },
  {
    type: ["Electric / e-Bike"],
    name: "Bike 13",
    city: "Mykolaiv",
    price: 5200,
  },
  { type: ["Gravel / Adventure"], name: "Bike 14", city: "Sumy", price: 1500 },
  {
    type: ["Hybrid / Commuter"],
    name: "Bike 15",
    city: "Poltava",
    price: 3800,
  },
  { type: ["Road / Racing"], name: "Bike 16", city: "Cherkasy", price: 2700 },
  {
    type: ["Mountain / Trail"],
    name: "Bike 17",
    city: "Zhytomyr",
    price: 4300,
  },
  {
    type: ["Electric / e-Bike"],
    name: "Bike 18",
    city: "Chernivtsi",
    price: 2000,
  },
  {
    type: ["Gravel / Adventure"],
    name: "Bike 19",
    city: "Kropyvnytskyi",
    price: 3100,
  },
  { type: ["Hybrid / Commuter"], name: "Bike 20", city: "Kharkiv", price: 700 },
  { type: ["Road / Racing"], name: "Bike 21", city: "Kyiv", price: 2900 },
  { type: ["Mountain / Trail"], name: "Bike 22", city: "Lviv", price: 4600 },
  { type: ["Electric / e-Bike"], name: "Bike 23", city: "Odessa", price: 1200 },
  {
    type: ["Gravel / Adventure"],
    name: "Bike 24",
    city: "Kharkiv",
    price: 5400,
  },
  { type: ["Hybrid / Commuter"], name: "Bike 25", city: "Dnipro", price: 3600 },
  { type: ["Road / Racing"], name: "Bike 26", city: "Vinnytsia", price: 1800 },
  {
    type: ["Mountain / Trail"],
    name: "Bike 27",
    city: "Chernihiv",
    price: 4700,
  },
  { type: ["Electric / e-Bike"], name: "Bike 28", city: "Lutsk", price: 900 },
  { type: ["Gravel / Adventure"], name: "Bike 29", city: "Rivne", price: 3900 },
  {
    type: ["Hybrid / Commuter"],
    name: "Bike 30",
    city: "Ivano-Frankivsk",
    price: 2500,
  },
];
